/*
 * This file is generated by jOOQ.
 */
package com.aldren.model.tables.records;


import com.aldren.model.tables.PokemonTypeMapper;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PokemonTypeMapperRecord extends UpdatableRecordImpl<PokemonTypeMapperRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1887986335;

    /**
     * Setter for <code>aldren.pokemon_type_mapper.pokemon_id</code>.
     */
    public void setPokemonId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aldren.pokemon_type_mapper.pokemon_id</code>.
     */
    public Integer getPokemonId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aldren.pokemon_type_mapper.type_id</code>.
     */
    public void setTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>aldren.pokemon_type_mapper.type_id</code>.
     */
    public Integer getTypeId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PokemonTypeMapper.POKEMON_TYPE_MAPPER.POKEMON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PokemonTypeMapper.POKEMON_TYPE_MAPPER.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPokemonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPokemonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonTypeMapperRecord value1(Integer value) {
        setPokemonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonTypeMapperRecord value2(Integer value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonTypeMapperRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PokemonTypeMapperRecord
     */
    public PokemonTypeMapperRecord() {
        super(PokemonTypeMapper.POKEMON_TYPE_MAPPER);
    }

    /**
     * Create a detached, initialised PokemonTypeMapperRecord
     */
    public PokemonTypeMapperRecord(Integer pokemonId, Integer typeId) {
        super(PokemonTypeMapper.POKEMON_TYPE_MAPPER);

        set(0, pokemonId);
        set(1, typeId);
    }
}
