/*
 * This file is generated by jOOQ.
 */
package com.aldren.model;


import com.aldren.model.tables.Pokemon;
import com.aldren.model.tables.PokemonType;
import com.aldren.model.tables.PokemonTypeMapper;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aldren extends SchemaImpl {

    private static final long serialVersionUID = -1764030625;

    /**
     * The reference instance of <code>aldren</code>
     */
    public static final Aldren ALDREN = new Aldren();

    /**
     * The table <code>aldren.pokemon</code>.
     */
    public final Pokemon POKEMON = Pokemon.POKEMON;

    /**
     * The table <code>aldren.pokemon_type</code>.
     */
    public final PokemonType POKEMON_TYPE = PokemonType.POKEMON_TYPE;

    /**
     * The table <code>aldren.pokemon_type_mapper</code>.
     */
    public final PokemonTypeMapper POKEMON_TYPE_MAPPER = PokemonTypeMapper.POKEMON_TYPE_MAPPER;

    /**
     * No further instances allowed
     */
    private Aldren() {
        super("aldren", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Pokemon.POKEMON,
            PokemonType.POKEMON_TYPE,
            PokemonTypeMapper.POKEMON_TYPE_MAPPER);
    }
}
