/*
 * This file is generated by jOOQ.
 */
package com.aldren.model;


import com.aldren.model.tables.Pokemon;
import com.aldren.model.tables.PokemonType;
import com.aldren.model.tables.PokemonTypeMapper;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>aldren</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index POKEMON_PRIMARY = Indexes0.POKEMON_PRIMARY;
    public static final Index POKEMON_TYPE_PRIMARY = Indexes0.POKEMON_TYPE_PRIMARY;
    public static final Index POKEMON_TYPE_MAPPER_PRIMARY = Indexes0.POKEMON_TYPE_MAPPER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index POKEMON_PRIMARY = Internal.createIndex("PRIMARY", Pokemon.POKEMON, new OrderField[] { Pokemon.POKEMON.ID }, true);
        public static Index POKEMON_TYPE_PRIMARY = Internal.createIndex("PRIMARY", PokemonType.POKEMON_TYPE, new OrderField[] { PokemonType.POKEMON_TYPE.ID }, true);
        public static Index POKEMON_TYPE_MAPPER_PRIMARY = Internal.createIndex("PRIMARY", PokemonTypeMapper.POKEMON_TYPE_MAPPER, new OrderField[] { PokemonTypeMapper.POKEMON_TYPE_MAPPER.POKEMON_ID, PokemonTypeMapper.POKEMON_TYPE_MAPPER.TYPE_ID }, true);
    }
}
