/*
 * This file is generated by jOOQ.
 */
package com.aldren.model;


import com.aldren.model.tables.Pokemon;
import com.aldren.model.tables.PokemonType;
import com.aldren.model.tables.PokemonTypeMapper;
import com.aldren.model.tables.records.PokemonRecord;
import com.aldren.model.tables.records.PokemonTypeMapperRecord;
import com.aldren.model.tables.records.PokemonTypeRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>aldren</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PokemonTypeRecord, Integer> IDENTITY_POKEMON_TYPE = Identities0.IDENTITY_POKEMON_TYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PokemonRecord> KEY_POKEMON_PRIMARY = UniqueKeys0.KEY_POKEMON_PRIMARY;
    public static final UniqueKey<PokemonTypeRecord> KEY_POKEMON_TYPE_PRIMARY = UniqueKeys0.KEY_POKEMON_TYPE_PRIMARY;
    public static final UniqueKey<PokemonTypeMapperRecord> KEY_POKEMON_TYPE_MAPPER_PRIMARY = UniqueKeys0.KEY_POKEMON_TYPE_MAPPER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PokemonTypeRecord, Integer> IDENTITY_POKEMON_TYPE = Internal.createIdentity(PokemonType.POKEMON_TYPE, PokemonType.POKEMON_TYPE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PokemonRecord> KEY_POKEMON_PRIMARY = Internal.createUniqueKey(Pokemon.POKEMON, "KEY_pokemon_PRIMARY", Pokemon.POKEMON.ID);
        public static final UniqueKey<PokemonTypeRecord> KEY_POKEMON_TYPE_PRIMARY = Internal.createUniqueKey(PokemonType.POKEMON_TYPE, "KEY_pokemon_type_PRIMARY", PokemonType.POKEMON_TYPE.ID);
        public static final UniqueKey<PokemonTypeMapperRecord> KEY_POKEMON_TYPE_MAPPER_PRIMARY = Internal.createUniqueKey(PokemonTypeMapper.POKEMON_TYPE_MAPPER, "KEY_pokemon_type_mapper_PRIMARY", PokemonTypeMapper.POKEMON_TYPE_MAPPER.POKEMON_ID, PokemonTypeMapper.POKEMON_TYPE_MAPPER.TYPE_ID);
    }
}
