es:
  instances: localhost:9200
  connection: http
  username: elastic
  password: changeme
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/aldren
    username: root
    password: mypass
    driverClassName: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1